spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "060571"
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db.changelog-master.xml

  freemarker:
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/templates/
    suffix: .ftl

